### ISSUE TITLE
Ecodevice

### ISSUE THREAD

**Issue by johndoe2011** [BmdOnline/Teleinfo#12]
Bonsoir,
je souhaiterais pouvoir utiliser les scripts avec l'Ecodevice .....j'ai vu que plusieurs avaient réussi.
Pourriez vous m'aider avec les modif à faire ? J'ai le fichier "teleinfov3" et j'ai mis dans le fichier structure-date.php :
"table" => array (
"DATE" => "DATE", // => généralement, vaut soit "DATE", soit "TIMESTAMP"
"OPTARIF" => "null", // option tarifaire souscrite
"ISOUSC" => "null", // intensité souscrite
"BASE" => "T1_BASE", // BASE
"HP" => "T1_HCHP", // HCHP
"HC" => "T1_HCHC", // HCHC
"HPJB" => "null", // BBRHPJB
"HPJW" => "null", // BBRHPJW
"HPJR" => "null", // BBRHPJR
"HCJB" => "null", // BBRHCJB
"HCJW" => "null", // BBRHCJW
"HCJR" => "null", // BBRHCJR
"HN" => "null", // EJPN
"HPM" => "null", // EJPHPM
"PTEC" => "T1_PTEC", // période tarifaire en cours
"DEMAIN" => "null", // prévision du lendemain (formule Tempo)
"IINST1" => "null", // => généralement, vaut soit "IINST1" soit "INST1"
"PAPP" => "T1_PAPP" // puissance apparente

et 
$teleinfo["OPTARIF"] = array(
"T1_BASE" => "BASE",
"T1_HCHC" => "HC",
"null" => "BBR",
"null" => "EPJ"

Par contre je n'ai pas de fichier structure.ecodevice_hchp.php

Merci d'avance

**Comment by Jay64** [comment]
Bonjour,

je cherche à intégrer ces scripts pour l'analyse de mon EcoDevice et abonnement Tempo d'EDF. J'ai parcouru les différents packages, surtout le dernier 4.2 mais je ne trouve aucun fichier structure.ecodevice_hchp.php. 
Ai-je loupé quelque chose ?

Merci

Jérôme
