### ISSUE TITLE
Problème de consomation en option BASE

### ISSUE THREAD

**Issue by Aior** [BmdOnline/Teleinfo#15]
Bonjour,

L'outil marche très bien, facile à mettre en place, bravo !

Cependant, je pense avoir un soucis sur la tarification.
En historique, sur 8 jours, avoir consommé 225,4 kWh et en avoir pour seulement 10,34 €, je pense qu'il y a un souci.

J'ai l'impression que le souci ce trouve au niveau du calcul du KWh consommé.
Sur 8 jours, les 10,34 € correspondent au total de l'abonnement et des taxes, mais ne compte pas la consomation.

J'ai essayé de debuggé comme j'ai pu, mais je ne trouve pas.

J'ai mis l'ensemble des infos sur pastebin http://pastebin.com/MdsGBaqN

Le problème se constate en branch master et en dev.

Un screenshot : http://oi58.tinypic.com/2ccql5k.jpg

Une idée du problème ou une orientation à donner ?

**Comment by BmdOnline** [comment]
Bonjour,
Je répond (très) tard. Désolé.

Le calcul de consommation est basé sur un fichier tarifs.php qui demande à vivre.
Les tarifs, en particulier les taxes, ne sont pas à jour.

Au delà de ça, il est fort possible qu'il y ait une erreur de calcul.
Là, c'est dans le programme qu'il faut aller voir... et c'est moins simple.
Ca se passe dans le fichier json.php, voir "Calcul des coûts".

**Comment by Aior** [comment]
Merci pour la réponse.

Le problème se corrige effectivement bien dans le fichier tarifs.php .
En rajoutant une valeur dans l'array $tarifs pour les périodes concernées : 
"BASE.12" => 1.20*0.0909,
Dans mon cas, étant en BASE 12 kVa.
http://i62.tinypic.com/33lcxec.jpg
Merci !
