### ISSUE TITLE
aucune info affichée

### ISSUE THREAD

**Issue by yves67** [BmdOnline/Teleinfo#18]
bonjour,
j'essaie d'utiliser votre superbe application, mais rien ne s'affiche
comment contrôler que l'accès à la base se fait bien ?
comment voir les messages d'erreurs ? ou débuger ? 
merci de votre aide
yves67

**Comment by BmdOnline** [comment]
Bonjour,
Le sujet a été évoqué plusieurs fois dans les anciennes "issues".
Pour faire les diagnostics de base :


Commenter la ligne "error_reporting(0);" dans json.php puis tester les requêtes en direct :
```
http:/.../json.php?query=instantly
http:/.../json.php?query=daily
http:/.../json.php?query=history
```
Et voir s'il y a des messages d'erreur.

**Comment by yves67** [comment]
bonjour
ok, merci
désolé pour avoir posé la question
je vais tester
merci
yves

Le 20 mai 2015 19:46, BmdOnline <notifications@github.com> a écrit :

> Bonjour,
> Le sujet a été évoqué plusieurs fois dans les anciennes "issues".
> Pour faire les diagnostics de base :
>
> Commenter la ligne "error_reporting(0);" dans json.php puis tester les
> requêtes en direct :
>
> http:/.../json.php?query=instantly
> http:/.../json.php?query=daily
> http:/.../json.php?query=history
>
> Et voir s'il y a des messages d'erreur.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/BmdOnline/Teleinfo/issues/18#issuecomment-103972027>.
>



-- 
Yves VOUIN - InfoPCServices - 06 75 87 43 34

**Comment by yves67** [comment]
rebonjour
je viens de corriger l'erreur (PAAP au lieu de PAPP) pour instantly
ça marche

pour le daily j'ai l"erreur suivante :

*Erreur* dans la requète *SELECT TIMESTAMP AS TIMESTAMP, 'BASE' AS OPTARIF,
'BASE' AS PTEC, IINST1 AS IINST1, PAPP AS PAPP FROM TabTeleInfo WHERE
TIMESTAMP BETWEEN -170785 and 2015-05-20 11:35:40 ORDER BY TIMESTAMP* : You
have an error in your SQL syntax; check the manual that corresponds to your
MariaDB server version for the right syntax to use near '11:35:40 ORDER BY
TIMESTAMP' at line 1 !

pour l'history : (je n'ai qu'une journée dans la base) j'ai l'erreur
suivante :

Warning: Invalid argument supplied for foreach() in
/volume1/web/AfficheInfo/json.php on line 506 Warning: mysql_data_seek():
Offset 0 is invalid for MySQL result index 5 (or the query data is
unbuffered) in /volume1/web/AfficheInfo/json.php on line 515 Warning:
Invalid argument supplied for foreach() in
/volume1/web/AfficheInfo/json.php on line 551 Warning: reset() expects
parameter 1 to be array, null given in /volume1/web/AfficheInfo/json.php on
line 557 Warning: Invalid argument supplied for foreach() in
/volume1/web/AfficheInfo/tarifs.php on line 389 Warning: Invalid argument
supplied for foreach() in /volume1/web/AfficheInfo/json.php on line 573
Warning: reset() expects parameter 1 to be array, null given in
/volume1/web/AfficheInfo/json.php on line 578 Warning: reset() expects
parameter 1 to be array, null given in /volume1/web/AfficheInfo/json.php on
line 578 Warning: Invalid argument supplied for foreach() in
/volume1/web/AfficheInfo/json.php on line 651 Warning: Invalid argument
supplied for foreach() in /volume1/web/AfficheInfo/json.php on line 654
Warning: array_sum() expects parameter 1 to be array, null given in
/volume1/web/AfficheInfo/json.php on line 657 Warning: array_sum() expects
parameter 1 to be array, null given in /volume1/web/AfficheInfo/json.php on
line 658 Warning: array_sum() expects parameter 1 to be array, null given
in /volume1/web/AfficheInfo/json.php on line 659 Warning: Invalid argument
supplied for foreach() in /volume1/web/AfficheInfo/json.php on line 662
Warning: Invalid argument supplied for foreach() in
/volume1/web/AfficheInfo/json.php on line 665 Warning: array_sum() expects
parameter 1 to be array, null given in /volume1/web/AfficheInfo/json.php on
line 668 Warning: array_sum() expects parameter 1 to be array, null given
in /volume1/web/AfficheInfo/json.php on line 669 Warning: array_sum()
expects parameter 1 to be array, null given in
/volume1/web/AfficheInfo/json.php on line 670 Warning: array_flip() expects
parameter 1 to be array, null given in /volume1/web/AfficheInfo/json.php on
line 724 Warning: array_intersect_key(): Argument #2 is not an array in
/volume1/web/AfficheInfo/json.php on line 724 Warning: Invalid argument
supplied for foreach() in /volume1/web/AfficheInfo/json.php on line 749
{"show3D":false,"title":"Consomation sur 8
jours","subtitle":"","optarif":{"":null},"ptec":{"":null},"duree":8,"periode":"jours","debut":82800000,"series":null,"prix":null,"prix_tot":{"ABONNEMENTS":null,"TOTAL":null,"KWH":null},"PREC_prix":null,"PREC_prix_tot":{"ABONNEMENTS":null,"TOTAL":null,"KWH":null},"categories":[null,null,null,null,null,null,null,null],"PREC_color":"#DB843D","PREC_name":"P\u00e9riode
Pr\u00e9c\u00e9dente","PREC_data":[],"PREC_data_detail":null,"PREC_type":"spline"}

merci de votre aide

yves

Le 20 mai 2015 19:46, BmdOnline <notifications@github.com> a écrit :

> Bonjour,
> Le sujet a été évoqué plusieurs fois dans les anciennes "issues".
> Pour faire les diagnostics de base :
>
> Commenter la ligne "error_reporting(0);" dans json.php puis tester les
> requêtes en direct :
>
> http:/.../json.php?query=instantly
> http:/.../json.php?query=daily
> http:/.../json.php?query=history
>
> Et voir s'il y a des messages d'erreur.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/BmdOnline/Teleinfo/issues/18#issuecomment-103972027>.
>



-- 
Yves VOUIN - InfoPCServices - 06 75 87 43 34

**Comment by yves67** [comment]
après lecture de json.php, je vais modifier ma table sql pour y ajouter
optarif, isousc et ptec
je ne les avais pas mis dans la table pour gagner de la place
je suis en triphasé, j'ai 15A par phase, Isousc = 15
mais mon contrat est un 45A, j'ai mis 3 dans config.php por le triphasé

est-ce correct

je ferai la modif demain et je vous tiens au courant

merci pour tout

Yves

2015-05-20 20:31 GMT+02:00 yves vouin <yves.vouin@gmail.com>:

> rebonjour
> je viens de corriger l'erreur (PAAP au lieu de PAPP) pour instantly
> ça marche
>
> pour le daily j'ai l"erreur suivante :
>
> *Erreur* dans la requète *SELECT TIMESTAMP AS TIMESTAMP, 'BASE' AS
> OPTARIF, 'BASE' AS PTEC, IINST1 AS IINST1, PAPP AS PAPP FROM TabTeleInfo
> WHERE TIMESTAMP BETWEEN -170785 and 2015-05-20 11:35:40 ORDER BY TIMESTAMP* :
> You have an error in your SQL syntax; check the manual that corresponds to
> your MariaDB server version for the right syntax to use near '11:35:40
> ORDER BY TIMESTAMP' at line 1 !
>
> pour l'history : (je n'ai qu'une journée dans la base) j'ai l'erreur
> suivante :
>
> Warning: Invalid argument supplied for foreach() in
> /volume1/web/AfficheInfo/json.php on line 506 Warning: mysql_data_seek():
> Offset 0 is invalid for MySQL result index 5 (or the query data is
> unbuffered) in /volume1/web/AfficheInfo/json.php on line 515 Warning:
> Invalid argument supplied for foreach() in
> /volume1/web/AfficheInfo/json.php on line 551 Warning: reset() expects
> parameter 1 to be array, null given in /volume1/web/AfficheInfo/json.php on
> line 557 Warning: Invalid argument supplied for foreach() in
> /volume1/web/AfficheInfo/tarifs.php on line 389 Warning: Invalid argument
> supplied for foreach() in /volume1/web/AfficheInfo/json.php on line 573
> Warning: reset() expects parameter 1 to be array, null given in
> /volume1/web/AfficheInfo/json.php on line 578 Warning: reset() expects
> parameter 1 to be array, null given in /volume1/web/AfficheInfo/json.php on
> line 578 Warning: Invalid argument supplied for foreach() in
> /volume1/web/AfficheInfo/json.php on line 651 Warning: Invalid argument
> supplied for foreach() in /volume1/web/AfficheInfo/json.php on line 654
> Warning: array_sum() expects parameter 1 to be array, null given in
> /volume1/web/AfficheInfo/json.php on line 657 Warning: array_sum() expects
> parameter 1 to be array, null given in /volume1/web/AfficheInfo/json.php on
> line 658 Warning: array_sum() expects parameter 1 to be array, null given
> in /volume1/web/AfficheInfo/json.php on line 659 Warning: Invalid argument
> supplied for foreach() in /volume1/web/AfficheInfo/json.php on line 662
> Warning: Invalid argument supplied for foreach() in
> /volume1/web/AfficheInfo/json.php on line 665 Warning: array_sum() expects
> parameter 1 to be array, null given in /volume1/web/AfficheInfo/json.php on
> line 668 Warning: array_sum() expects parameter 1 to be array, null given
> in /volume1/web/AfficheInfo/json.php on line 669 Warning: array_sum()
> expects parameter 1 to be array, null given in
> /volume1/web/AfficheInfo/json.php on line 670 Warning: array_flip() expects
> parameter 1 to be array, null given in /volume1/web/AfficheInfo/json.php on
> line 724 Warning: array_intersect_key(): Argument #2 is not an array in
> /volume1/web/AfficheInfo/json.php on line 724 Warning: Invalid argument
> supplied for foreach() in /volume1/web/AfficheInfo/json.php on line 749
> {"show3D":false,"title":"Consomation sur 8
> jours","subtitle":"","optarif":{"":null},"ptec":{"":null},"duree":8,"periode":"jours","debut":82800000,"series":null,"prix":null,"prix_tot":{"ABONNEMENTS":null,"TOTAL":null,"KWH":null},"PREC_prix":null,"PREC_prix_tot":{"ABONNEMENTS":null,"TOTAL":null,"KWH":null},"categories":[null,null,null,null,null,null,null,null],"PREC_color":"#DB843D","PREC_name":"P\u00e9riode
> Pr\u00e9c\u00e9dente","PREC_data":[],"PREC_data_detail":null,"PREC_type":"spline"}
>
> merci de votre aide
>
> yves
>
> Le 20 mai 2015 19:46, BmdOnline <notifications@github.com> a écrit :
>
>> Bonjour,
>> Le sujet a été évoqué plusieurs fois dans les anciennes "issues".
>> Pour faire les diagnostics de base :
>>
>> Commenter la ligne "error_reporting(0);" dans json.php puis tester les
>> requêtes en direct :
>>
>> http:/.../json.php?query=instantly
>> http:/.../json.php?query=daily
>> http:/.../json.php?query=history
>>
>> Et voir s'il y a des messages d'erreur.
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/BmdOnline/Teleinfo/issues/18#issuecomment-103972027>.
>>
>
>
>
> --
> Yves VOUIN - InfoPCServices - 06 75 87 43 34
>



-- 
Yves VOUIN - InfoPCServices - 06 75 87 43 34

**Comment by BmdOnline** [comment]
Sinon il faut modifier le ficher qui décrit la structure de la table.
En mettant NULL, pour certains champs ca devrait passer. Ou la valeur en direct par exemple le fameux 15 pour isousc.
Je réponds ça de mémoire. Il faut tester.

**Comment by yves67** [comment]
Bonjour
j'ai modifié ma t

Le 20 mai 2015 23:58, BmdOnline <notifications@github.com> a écrit :

> Sinon il faut modifier le ficher qui décrit la structure de la table.
> En mettant NULL, pour certains champs ca devrait passer. Ou la valeur en
> direct par exemple le fameux 15 pour isousc.
> Je réponds ça de mémoire. Il faut tester.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/BmdOnline/Teleinfo/issues/18#issuecomment-104051441>.
>



-- 
Yves VOUIN - InfoPCServices - 06 75 87 43 34

**Comment by yves67** [comment]
Bonjour
J'ai modifié ma table SQL pour y incorporer OPTARIF, ISOUSC et PTEC
j'ai un champ TS qui est un TimeStamp, il contient la date et l'heure de
l'enregistrement
mais j'ai un problème avec ce champ
avec json.phpquery=instantly
si j'affiche avec echo le champ date_deb j'obtiens :* 2015-05-20 22:26:16*
ce qui me parait correct
puis j'affiche le champ date_text et là j'obtiens : *Thu Jan 1 01:33:35
1970*

$datetext = date("d/m G:i", $date_deb);

bizarre ???
j'ai vu un autre post qui avait le même problème mais je n'ai pas vu la
solution ???

avez-vous une idée ?

merci de votre aide

Yves

Le 21 mai 2015 18:40, yves vouin <yves.vouin@gmail.com> a écrit :

> Bonjour
> j'ai modifié ma t
>
> Le 20 mai 2015 23:58, BmdOnline <notifications@github.com> a écrit :
>
>> Sinon il faut modifier le ficher qui décrit la structure de la table.
>> En mettant NULL, pour certains champs ca devrait passer. Ou la valeur en
>> direct par exemple le fameux 15 pour isousc.
>> Je réponds ça de mémoire. Il faut tester.
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/BmdOnline/Teleinfo/issues/18#issuecomment-104051441>.
>>
>
>
>
> --
> Yves VOUIN - InfoPCServices - 06 75 87 43 34
>



-- 
Yves VOUIN - InfoPCServices - 06 75 87 43 34

**Comment by BmdOnline** [comment]
En principe, en utilisant le bon fichier 'structure.timestp.php', il ne devrait pas y avoir de problème.
Vous avez configuré ça comment ? Avec quel fichier 'structure' ?
L'idée était de faire un système assez ouvert, avec juste un peu de paramétrage pour gérer tous les formats de base possibles.

**Comment by yves67** [comment]
Bonjour
Merci de votre réponse
voici quelques éléments qui permettront de voir où est mon erreur
1- je suis en triphasé 3 x 15A, option BASE  (pas de jour/nuit)
2- j'utilise le fichier structure.timestp.php (je vous le mets en pièce
jointe)
3- je vous mets aussi la structure de ma table SQL
4- l'option instantanée fonctionne, mais affiche une date erronée



Je pense que j'ai un problème au niveau du timestamp, mais je ne vois pas
où est mon erreur

merci de votre aide

Yves

Le 22 mai 2015 00:07, BmdOnline <notifications@github.com> a écrit :

> En principe, en utilisant le bon fichier 'structure.timestp.php', il ne
> devrait pas y avoir de problème.
> Vous avez configuré ça comment ? Avec quel fichier 'structure' ?
> L'idée était de faire un système assez ouvert, avec juste un peu de
> paramétrage pour gérer tous les formats de base possibles.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/BmdOnline/Teleinfo/issues/18#issuecomment-104435438>.
>



-- 
Yves VOUIN - InfoPCServices - 06 75 87 43 34

**Comment by yves67** [comment]
rebonjour
je viens de changer le type de date, j'ai mis DATE au lieu de Timestamp et
ça marche .......

bizarre, j'ai bien TimeStamp dans ma base SQL

comprends pas, mais le principal c'est que cela fonctionne

pour le calcul des coûts, est-ce que vous tenez compte du triphasé ?

merci pour tout

Yves

Le 22 mai 2015 08:55, yves vouin <yves.vouin@gmail.com> a écrit :

> Bonjour
> Merci de votre réponse
> voici quelques éléments qui permettront de voir où est mon erreur
> 1- je suis en triphasé 3 x 15A, option BASE  (pas de jour/nuit)
> 2- j'utilise le fichier structure.timestp.php (je vous le mets en pièce
> jointe)
> 3- je vous mets aussi la structure de ma table SQL
> 4- l'option instantanée fonctionne, mais affiche une date erronée
>
>
>
> Je pense que j'ai un problème au niveau du timestamp, mais je ne vois pas
> où est mon erreur
>
> merci de votre aide
>
> Yves
>
> Le 22 mai 2015 00:07, BmdOnline <notifications@github.com> a écrit :
>
>> En principe, en utilisant le bon fichier 'structure.timestp.php', il ne
>> devrait pas y avoir de problème.
>> Vous avez configuré ça comment ? Avec quel fichier 'structure' ?
>> L'idée était de faire un système assez ouvert, avec juste un peu de
>> paramétrage pour gérer tous les formats de base possibles.
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/BmdOnline/Teleinfo/issues/18#issuecomment-104435438>.
>>
>
>
>
> --
> Yves VOUIN - InfoPCServices - 06 75 87 43 34
>



-- 
Yves VOUIN - InfoPCServices - 06 75 87 43 34

**Comment by BmdOnline** [comment]
J'ai créé un fichier qui contient la "grille des taux" d'EDF.
Il faut mettre à jour ce fichier car il ne l'est plus.
Il faut aussi mettre à jour les différentes taxes, qui ne sont pas toutes nationales.

De mon coté, j'ai du monophasé. Pour le triphasé, ça devrait aussi marcher mais je ne peux pas l'assurer.

Pour revenir au Timestamp / Datetime, on parle bien du type de la donnée, pas de son nom.
C'est étonnant, mais si ça marche, c'est l'essentiel.

**Comment by yves67** [comment]
bonjour merci pour votre réponse
ok pour les tarifs je vais regarder cela
pour la date, en fait dans SQL c'est du TimeStamp mais la data est
enregistrée sous forme de date, donc c'est du date
la poisse continue, depuis ce matin je ne reçois plus de trame, après
investigation il s'avère que le compteur EDF triphasé a un bug, et n'envoie
pas les trames correctement (pas de RC), c'est un bug connu uniquement sur
les compteurs triphasés, j'ai téléphoné à EDF pour avoir un remplacement et
un nouveau modèle (qui n'a pas le bug)
on va y arriver....

encore merci pour votre aide

cordialement

Yves VOUIN

Le 22 mai 2015 19:13, BmdOnline <notifications@github.com> a écrit :

> J'ai créé un fichier qui contient la "grille des taux" d'EDF.
> Il faut mettre à jour ce fichier car il ne l'est plus.
> Il faut aussi mettre à jour les différentes taxes, qui ne sont pas toutes
> nationales.
>
> De mon coté, j'ai du monophasé. Pour le triphasé, ça devrait aussi marcher
> mais je ne peux pas l'assurer.
>
> Pour revenir au Timestamp / Datetime, on parle bien du type de la donnée,
> pas de son nom.
> C'est étonnant, mais si ça marche, c'est l'essentiel.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/BmdOnline/Teleinfo/issues/18#issuecomment-104717709>.
>



-- 
Yves VOUIN - InfoPCServices - 06 75 87 43 34
