### ISSUE TITLE
Compteur sans info "papp"

### ISSUE THREAD

**Issue by stephaneSBO** [BmdOnline/Teleinfo#19]
Bonjour Antony 

J'utilisais historiquement la version 3 des scripts, et je suis tombé dernièrement sur cette version qui est vraiment de belle facture.

Mon problème, j'utilise un ancien compteur qui de fournit pas l'info papp (premiere version du compteur).

Le recalcule "recalculPuissance" me permet de palier à ce problème pour l'aperçu et l'historique.

Hélas le recalcule ne semble pas s'appliquer à la gauge puissance. Cette dernière reste figée à zero. Par de problème pour l'intensité.

Est'il possible de prendre en compte le recalcule pour la gauge de puissance ?

Merci par avance.

Stéphane

**Comment by BmdOnline** [comment]
La puissance recalculée est basée sur un écart de consommation (index relevé au compteur) entre 2 mesures.

Pour l'instant, le recalcul ne se fait que dans le graphique sur 24h.

On pourrait prévoir recalculer la gauge, mais je ne suis pas convaincu du résultat : on n'aurait plus une lecture instantanée, mais un écart par rapport au relevé précédent.
Ça perd sons sens.
