### ISSUE TITLE
Affichage conso instannée avec PAPP, (Autoconsomation Photovoltaique), Affichage Index HC HP (Dume Loic)

### ISSUE THREAD

**Issue by dumeloic** [BmdOnline/Teleinfo#22]
Bonjour, je tiens a vous félicitez pour votre travail, c'est vraiment super.
Je peu vous apportez ma contribution par un script en python qui relève toute les étiquettes teleinfo.
Petite remarque à vous faire:
L'affichage de consommation instantanée se fait par le relevé de l'étiquette PAPP dans la BDD.
Dommage que vous n'utilisez pas la comparaison de la valeur HCHP entre deux injection dans la BDD. 
Cette option est très utile dans mon cas, car je fais de l'autoconsommation avec des panneaux photovoltaïques.
Quand je produit plus que ce je consomme, le compteur m’indique la puissance instantanée que je réinjecte. Il ne sait pas faire la différence entre consommation et une injection....
Je travaille sur affichage de l'index Heures Creuses et Heures Pleines sur la page "Instantané", pratique quand vous utiliser le relever de confiances EDF.
Sincères Salutations

**Comment by BmdOnline** [comment]
Dans le fichier ``config.php``
```
$config["recalculPuissance"]     = false; // true : calcule la puissance en se basant sur le relevé d'index plutôt que PAPP
```
Cette option permet de recalculer la consommation instantanée.

**Comment by cadegenn** [comment]
bonjour,

La 2ème partie de la question est résolue dans le pull request #26 
bonne soirée
