### ISSUE TITLE
Utiliser Mysqli ou  PDO_MySQL

### ISSUE THREAD

**Issue by jmgfr** [BmdOnline/Teleinfo#24]
Bonjour et merci pour cet excellent outil.

Apres mise a jour de mon serveur vers une version plus récente de l'OS, cet outil ne fonctionne malheureusement plus avec php 7 qui a retiré l'extension MySQL.

Vous serait-il possible de mettre a jour le code en utilisant MySQLi ou PDO_MySQL ?

Merci

**Comment by BmdOnline** [comment]
Je vais regarder ça.
Ça devrait être une modification assez simple : tout se passe dans ``json.php``

**Comment by BmdOnline** [comment]
C'est fait dans la branche dev
