### ISSUE TITLE
Aucun affichage

### ISSUE THREAD

**Issue by Xav33390** [BmdOnline/Teleinfo#25]
Bonjour tout le monde,
Très joli travail que celui fait ici.
Je suis novice en tout ce qui concerne la téléinfo et la programmation.
Je possède un raspberry pi2 avec une carte RPIDOM V2 pour la capture de la téléinfo de mon compteur EDF (monophasé, sans option particulière, tarif de base)
J'ai suivi pas à pas le descriptif, le fichier teleinfo.py me ramène les informations suivantes : 
![image](https://cloud.githubusercontent.com/assets/20799371/17365258/65569e66-5985-11e6-94d8-c2bedbf6dcf9.png)
mais quand je passe à la partie graphique, rien ne se passe.
Qu’ai-je raté ? Je paramètre le config.php comme il faut pour la connexion à la base de données. Mon souci est que je ne sais pas quel fichier structure.php choisir car le PTEC me ramène TH.. (donc avec des points) ce qui voudrait dire que je choisi le fichier structure.date.php, mais je n’ai comme nom IINST et non IINST1, donc ce devrait être le fichier structure.ftimestp.php… je suis perdu…
Merci de votre aide.
Xavier

**Comment by BmdOnline** [comment]
Il faut probablement faire un mix de tout ça.
Les champs de la base de donnée doivent correspondre, mais aussi les libellés renvoyés (effectivement avec/sans les points).

**Comment by cadegenn** [comment]
bonjour,

vous vous en êtes sorti ? je voulais répondre plus tôt, mais mon raspberry était planté depuis quelques mois sans que j'ai le temps de me remettre dedans... bref, il est de retour et pour répondre à votre question, je pense qu'il vaut mieux utiliser le fichier structure.date.php, en modifiant cette ligne : 
```php
         "IINST1"   => "IINST1",     // => généralement, vaut soit "IINST1" soit "INST1"
```
par
```php
        "IINST1"   => "IINST",     // => généralement, vaut soit "IINST1" soit "INST1" ou des fois IINST ;)
```
c'est la ligne 35.

J'en profite pour remercier l'auteur pour cette superbe appli
a+
