### ISSUE TITLE
Affichage totalement farfelu dans les historiques

### ISSUE THREAD

**Issue by cbrassel** [BmdOnline/Teleinfo#29]
Bonjour,

j'utilise depuis peu votre logiciel qui me convient parfaitement et qui est par ailleurs superbe !
Par contre depuis hier je rencontre des soucis dans l'affichage de l'historique : [capture historique](http://www.brassel.net/capture-historique.png)

J'ai vérifié dans la base et les entrées sont cohérente (les jours rouges n'on pas bougé depuis le début et les jours blanc sont stable depuis ce matin 6h (changement du tarif blanc au bleu), une idée ?

Par ailleurs j'aurais une petite question .. serait-il possible d'ajouter la possibilité de changer la couleur de fond des compteurs en fonction de la couleur du jour ? ce serait super ..

Merci pour votre travail !

Cordialement
C. Brassel

**Comment by BmdOnline** [comment]
Bonjour,
Quelle version avez-vous ? Une ancienne ou la dernière (dev) ?

Là, comme ça, j'ai un peu de mal à diagnostiquer !
Par contre, j'ai corrigé un défaut qui se produisait lors des changements d'heures. Peut-être est-ce lié ?

Testez la dernière version "dev" pour voir.

Dans cette version, j'implémente de nouvelles librairies graphiques.
Pour conserver l'apparence précédente (HighCharts), il faut éditer le fichier `js/teleinfo.js` et adapter les commentaires lignes 40 à 43.
Pour l'instant, la librairie activée par défaut (Flot) pose quelques soucis de Gauge avec Chrome.


En parallèle, je note l'idée des couleurs... pour plus tard...

**Comment by cbrassel** [comment]
Bonjour,

merci pour votre réponse ..

alors j’ai utilisé la dernière master .. qui fonctionnait d’ailleurs très bien pendant quelques jours, (je l’ai mis en service après le changement d’heures, donc à priori pas de rapport) ..

Je viens d’essayer la version de dev et c’est pareil (http://teleinfo.brassel.net:3520 <http://teleinfo.brassel.net:3520/>) 

J’ai vérifié la cohérence des données dans la base et ça à l’air correcte :
mysql> select * from maison order by TIMESTAMP limit 10;
+---------------------+---------+--------+------+------+------+----------+---------+---------+---------+---------+---------+-------+--------+------+--------+--------+------+
| TIMESTAMP           | OPTARIF | ISOUSC | BASE | HCHP | HCHC | BBRHPJB  | BBRHPJW | BBRHPJR | BBRHCJB | BBRHCJW | BBRHCJR | EJPHN | EJPHPM | PTEC | DEMAIN | IINST1 | PAPP |
+---------------------+---------+--------+------+------+------+----------+---------+---------+---------+---------+---------+-------+--------+------+--------+--------+------+
| 2016-11-09 14:09:51 | BBR     |     60 |    0 |    0 |    0 | 23663516 | 4458967 | 2081633 | 7091177 | 1521477 |  788899 |     0 |      0 | HPJB | ----   |      7 | 1610 |
| 2016-11-09 14:10:14 | BBR     |     60 |    0 |    0 |    0 | 23663526 | 4458967 | 2081633 | 7091177 | 1521477 |  788899 |     0 |      0 | HPJB | ----   |      7 | 1650 |
| 2016-11-09 14:10:37 | BBR     |     60 |    0 |    0 |    0 | 23663536 | 4458967 | 2081633 | 7091177 | 1521477 |  788899 |     0 |      0 | HPJB | ----   |      7 | 1620 |
| 2016-11-09 14:11:00 | BBR     |     60 |    0 |    0 |    0 | 23663546 | 4458967 | 2081633 | 7091177 | 1521477 |  788899 |     0 |      0 | HPJB | ----   |      7 | 1630 |
| 2016-11-09 14:11:23 | BBR     |     60 |    0 |    0 |    0 | 23663556 | 4458967 | 2081633 | 7091177 | 1521477 |  788899 |     0 |      0 | HPJB | ----   |      7 | 1630 |
| 2016-11-09 14:11:45 | BBR     |     60 |    0 |    0 |    0 | 23663566 | 4458967 | 2081633 | 7091177 | 1521477 |  788899 |     0 |      0 | HPJB | ----   |      7 | 1640 |
| 2016-11-09 14:12:06 | BBR     |     60 |    0 |    0 |    0 | 23663575 | 4458967 | 2081633 | 7091177 | 1521477 |  788899 |     0 |      0 | HPJB | ----   |      7 | 1630 |
| 2016-11-09 14:12:27 | BBR     |     60 |    0 |    0 |    0 | 23663584 | 4458967 | 2081633 | 7091177 | 1521477 |  788899 |     0 |      0 | HPJB | ----   |      7 | 1660 |
| 2016-11-09 14:12:50 | BBR     |     60 |    0 |    0 |    0 | 23663594 | 4458967 | 2081633 | 7091177 | 1521477 |  788899 |     0 |      0 | HPJB | ----   |      7 | 1690 |
| 2016-11-09 14:13:13 | BBR     |     60 |    0 |    0 |    0 | 23663605 | 4458967 | 2081633 | 7091177 | 1521477 |  788899 |     0 |      0 | HPJB | ----   |      8 | 1860 |
+---------------------+---------+--------+------+------+------+----------+---------+---------+---------+---------+---------+-------+--------+------+--------+--------+------+
10 rows in set (0.00 sec)

Je prend une mesure toutes les 20 secondes .. c’est peut-être un peu trop fréquent ?

J’ai eu le même type de bug au début je prenait les mesures comme le compteur me les donnais (donc 1 toutes les 2 à 3 secondes) et ça me remontait pareil des chiffres assez étonnant !

je vais faire le test et dropper la table pour voir .. à moins que vous ayez une autre idée ?

Cordialement
C. Brassel

**Comment by BmdOnline** [comment]
Avec l'accès à votre page (merci pour le lien), je regarderai ce soir si je vois quelque chose de choquant (retour du json, débuggage du javascript).

**Comment by BmdOnline** [comment]
Alors, la partie javascript fonctionne bien. C'est le retour php des données historiques qui est faux.
Là, je ne peux rien faire d'ici.
Serait-il possible de me transmettre un export de la table mysql ?

**Comment by cbrassel** [comment]
oui pas de soucis .. surtout qu’elle est encore assez petite :)

la voilà :

**Comment by BmdOnline** [comment]
Les pièces jointes ne passent lors d'une utilisation par mail.
Le mieux est d'utiliser un dépôt de fichiers, gist ou autre chose.

**Comment by cbrassel** [comment]
pas de soucis .. je ne manque pas de serveurs :)

http://teleinfo.brassel.net:3520/teleinfo.sql.gz

**Comment by BmdOnline** [comment]
C'est bon, j'ai identifié l'erreur :
```SQL
SELECT * FROM `maison`
WHERE (BBRHPJB = 0)
OR (BBRHPJW = 0)
OR (BBRHPJR = 0)
OR (BBRHCJB = 0)
OR (BBRHCJW = 0)
OR (BBRHCJR = 0)
ORDER BY TIMESTAMP
```

Retourne des éléments à zéro
```
"2016-11-14 11:58:40","BBR","60","0","0","0","23751497","4463965","2081633","7121624","0","0","0","0","HPJW","----","11","2610"
"2016-11-15 08:19:57","BBR","60","0","0","0","23753031","0","2081633","7121624","1525463","0","0","0","HPJB","----","9","2030"
"2016-11-15 10:07:10","BBR","60","0","0","0","23754455","4474278","2081633","7121624","0","788899","0","0","HPJB","----","3","810"
"2016-11-15 19:49:31","BBR","60","0","0","0","23765559","4474278","2081633","0","1525463","788899","0","0","HPJB","----","13","3010"
"2016-11-15 20:23:16","BBR","60","0","0","0","23766268","4474278","2081633","7121624","0","788899","0","0","HPJB","BLEU","4","1080"
"2016-11-16 05:05:38","BBR","60","0","0","0","23767671","4474278","2081633","7125496","1525463","0","0","0","HCJB","BLEU","2","530"
"2016-11-16 05:08:14","BBR","60","0","0","0","0","4474278","2081633","0","1525463","788899","0","0","HCJB","BLEU","2","540"
```

Curieusement, dans la table, il semblerait que les données ne soient pas à zéro
```SQL
INSERT INTO `maison` (`TIMESTAMP`, `OPTARIF`, `ISOUSC`, `BASE`, `HCHP`, `HCHC`, `BBRHPJB`, `BBRHPJW`, `BBRHPJR`, `BBRHCJB`, `BBRHCJW`, `BBRHCJR`, `EJPHN`, `EJPHPM`, `PTEC`, `DEMAIN`, `IINST1`, `PAPP`) VALUES
('2016-11-14 11:58:40', 'BBR', 60, 0, 0, 0, 23751497, 4464840, 2081633, 7121624, 1521477, 788899, 0, 0, 'HPJW', '----', 2, 540),
('2016-11-15 08:19:57', 'BBR', 60, 0, 0, 0, 23753834, 4474278, 2081633, 7121624, 1525463, 788899, 0, 0, 'HPJB', '----', 4, 960),
('2016-11-15 10:07:10', 'BBR', 60, 0, 0, 0, 23755260, 4474278, 2081633, 7121624, 1525463, 788899, 0, 0, 'HPJB', '----', 4, 890),
('2016-11-15 19:49:31', 'BBR', 60, 0, 0, 0, 23766662, 4474278, 2081633, 7121624, 1525463, 788899, 0, 0, 'HPJB', 'BLEU', 4, 860),
('2016-11-15 20:23:16', 'BBR', 60, 0, 0, 0, 23767115, 4474278, 2081633, 7121624, 1525463, 788899, 0, 0, 'HPJB', 'BLEU', 4, 980),
('2016-11-16 05:05:38', 'BBR', 60, 0, 0, 0, 23767707, 4474278, 2081633, 7126122, 1525463, 788899, 0, 0, 'HPJB', 'BLEU', 3, 610),
('2016-11-16 05:08:14', 'BBR', 60, 0, 0, 0, 23767735, 4474278, 2081633, 7126122, 1525463, 788899, 0, 0, 'HPJB', '----', 9, 2110);
```

Probablement un caractère exotique dans le fichier, transmis lors du relevé téléinfo.

La solution est de supprimer ces enregistrements.
```SQL
DELETE FROM `maison`
WHERE (BBRHPJB = 0)
OR (BBRHPJW = 0)
OR (BBRHPJR = 0)
OR (BBRHCJB = 0)
OR (BBRHCJW = 0)
OR (BBRHCJR = 0)
```

En parallèle, je peux essayer de "neutraliser" ces données lors de la requête, mais je ne sais pas quel sera l'impact sur le temps d'exécution.

**Comment by cbrassel** [comment]
super ! 

ça marche nickel .. je les avaient bien vu et trouvé un peu louche .. mais je n’ai pas fait le lien .. désolé .. 

je vais rajouter un test au niveau de mon script d’injection pour simplement éviter d’injecter des données null ce sera plus sain .. ceci dit un petit test au moment de la récupération des données ne peu sans doute pas faire de mal non plus .. 

Encore merci
Cordialement
C. Brassel

**Comment by BmdOnline** [comment]
Résolu 69fa91d237deccde8f1ceb43488e64328700d431
