### ISSUE TITLE
Problème d'affichage sur Safari iOS (iPhone : iPad)

### ISSUE THREAD

**Issue by Olivier6767** [BmdOnline/Teleinfo#31]
Bonjour,
J'utilise depuis 2014 votre interface qui fonctionne à merveille. 
Je viens de mettre à jour ma version 4.3 vers la nouvelle version 4.6 et j'ai un petit bug d'affichage avec le navigateur Safari sur iOS (iPhone et iPad).
Pendant le chargement il y des éléments calendrier superposés qui disparraissent partiellement à la fin du chargement de la page. Néanmoins il reste toujours une partie du calandrier en haut à gauche.
Ce problème n'existait pas dans la version 4.3

Y a t'il un moyen de le corriger ?

Merci.
Olivier

![new_chargement](https://cloud.githubusercontent.com/assets/28684355/26032615/f90328e0-3897-11e7-8b48-95fca7296294.PNG)
![new_history](https://cloud.githubusercontent.com/assets/28684355/26032616/f906c84c-3897-11e7-9a14-bdd713c4d6e0.PNG)
![new_instant](https://cloud.githubusercontent.com/assets/28684355/26032617/f90a70fa-3897-11e7-814f-1d11e52a7ac0.PNG)
![old_instant](https://cloud.githubusercontent.com/assets/28684355/26032618/f90f5aca-3897-11e7-8c2f-6528166580ed.PNG)

**Comment by phil69210** [comment]
Bonjour, tout d'abord merci pour le super boulot et pour le partage. Je n'ai pas eu trop de mal à mettre en place votre solution sur un Rapsberry Pi. J'utilise la version de développements.
J'ai le même souci avec un mobile Android ou tout simplement en activant l'outil de développement de Chrome et en sélectionnant un modèle de mobile. Le plugin jQuery DatePicker n'est pas rendu correctement car il manque la feuille de styles jquery-ui. Dans "teleinfo.tabs.mobile.html" la feuille est chargée depuis "./css/jquery/base/jquery-ui-1.12.1.min.css" et ce fichier n'est pas présent à cet endroit. Il est fourni dans "./vendor/css/jquery/base". Il faut donc modifier l'url dans le fichier et ajouter "vendor".

**Comment by Olivier6767** [comment]
J'ai fait la modification de l'url du fichier css et l'affichage est ok maintenant.
Merci pour l'info !
