### ISSUE TITLE
Aucun affichage PHP

### ISSUE THREAD

**Issue by Raspalex76** [BmdOnline/Teleinfo#34]
Bonjour,
J'ai beau parcourir plein de forum et les Issues fermés, je ne comprends toujours pas pourquoi j'ai une page blanche.
J'ai bien installé PHP7.0, Mysql, PHPmyadmin en suivant :
 https://dahoo.fr/wordpress/raspberry-pi-installer-serveur-web-complet/
et Teleinfo.git suivant ce tuto mais la procédure est un peu trop simplifiée pour moi. (il manque des étapes détaillées !)
J'ai du oublié de modifier des infos mais je ne sais pas où.

Alors je cris "HELP !!"

Je me debrouille pour la "manipulation" de fichiers su Pi mais je pèche un peu avec Mysql et les vérifications du bon fonctionnement....
Merci pour votre aide

**Comment by Bren75** [comment]
Bonjour,
j'ai également un problème : le site s'affiche bien, la connexion à la base de donnée est bien configurée.
Mon problème : je ne trouve pas la commande à intégrer dans un crontab pour alimenter la base de donnée

**Comment by kenji21** [comment]
C'est tsBdd.php:

```
* tsBdd.php
* Collecte et sauve la trame Teleinfo issue d'un TeleinfoStick dans une base de donnees.
```

la ligne cron:

```
# m h  dom mon dow   command
*/5 * * * * cd /var/www/tss && php tsBdd.php
```

**Comment by Bren75** [comment]
Merci beaucoup kenji21, mais je ne vois pas le fichier tsBdd.php dans le répertoire...

**Comment by kenji21** [comment]
I don't remember how I got since it was few years ago:

```
-rwxr-xr-x  1 pi www-data 3191 Nov 24  2013 tsBdd.php

$ svn log -l 1
svn: warning: cannot set LC_CTYPE locale
svn: warning: environment variable LC_ALL is en_US.UTF-8
svn: warning: please check that your locale name is correct
svn: E160013: Unable to connect to a repository at URL 'http://teleinfosticksystem.googlecode.com/svn/trunk'
svn: E160013: 'http://teleinfosticksystem.googlecode.com/svn/trunk' path not found
```

And it seems project migrated from googlecode to GitHub:

https://github.com/lamen/infoconso
