### ISSUE TITLE
Alimentation de la base de donnée

### ISSUE THREAD

**Issue by Bren75** [BmdOnline/Teleinfo#35]
Bonjour,

merci pour ce partage. J'ai installé le programme et créé la base de donnée. L'affichage se fait bien. Mon seul problème est que je ne trouve pas la commande à intégrer dans un crontab pour alimenter la base de donnée...

Est ce que quelqu'un pourrait me dépanner ?

Merci par avance !

**Comment by BmdOnline** [comment]
Pas de lien avec Teleinfo
