### ISSUE TITLE
Problème avec le graph 24h avec l'option tempo

### ISSUE THREAD

**Issue by MrFusion25** [BmdOnline/Teleinfo#36]
La vue 24h lors ce qu'on est en option tempo semble avoir un problème. La courbe de puissance du jour actuel ne s'affiche pas.
la courbe du jour précédent sans les détails de tarifs elle fonctionnent très bien ainsi que les vues historique et instantanée.
Il semble y avoir un problème avec les séries de données des différents tarifs.

![24h](https://github.com/BmdOnline/Teleinfo/assets/77106955/c8512736-2297-4489-924b-f8f57b8b34a8)

**Comment by BmdOnline** [comment]
Bonjour,
suite à nos échanges, pour résumer :
attention à ce que la base de donnée soit bien conforme.
Notamment la longueur des champs pour ne par tronquer les remontées teleinfo.

En l’occurrence, le champ PTEC était bel et bien tronqué.
C'est lui qui permet de savoir à un instant T quelle donnée afficher.
